# Site settings
title: William Chargin
email: wchargin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is my personal website and portfolio.
    It's currently under construction.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wchargin.github.io" # the base hostname & protocol for your site
highlighter: pygments
github_username: wchargin

# Build settings
markdown: kramdown
